import { NextResponse } from "next/server";
import { z } from "zod";
import { HttpError, clientIp, handle, rateLimit } from "@/lib/http";
import { getLLM } from "@/lib/providers";
import { loadAgent, prepareAnswer, saveAnswer, usedCitations } from "@/lib/answer";
import { refundCredit } from "@/lib/usage";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Ctx = { params: Promise<{ agentId: string }> };

const schema = z.object({
  message: z.string().trim().min(1, "Type a message").max(2000, "Message is too long"),
  // Random id generated by the browser; identifies one visitor's conversation.
  sessionId: z.string().regex(/^[A-Za-z0-9_-]{8,64}$/),
  channel: z.enum(["widget", "playground"]).optional().default("widget"),
});

/**
 * Public endpoint (called by the embeddable widget and the dashboard playground).
 * Streams newline-delimited JSON:
 *   {"type":"delta","text":"..."}  ...  {"type":"done","citations":[...]}   or   {"type":"error","message":"..."}
 * When a person (not the bot) is handling the conversation the stream is just
 *   {"type":"handoff","notice":"..."|null}  {"type":"done","citations":[]}
 * and the widget then polls GET /api/chat/:agentId/messages for the owner's replies.
 * Conversation history is read from the database, never trusted from the client.
 */
export const POST = handle<Ctx>(async (req, { params }) => {
  const agentId = (await params).agentId;
  if (!/^[0-9a-f-]{36}$/i.test(agentId)) throw new HttpError(404, "Agent not found");
  const { message, sessionId, channel } = schema.parse(await req.json());

  if (!rateLimit(`chat:${clientIp(req)}:${agentId}`, 20, 60_000)) throw new HttpError(429, "You're sending messages too quickly. Please wait a moment.");

  const agent = await loadAgent(agentId);
  if (!agent) throw new HttpError(404, "Agent not found");

  const prepared = await prepareAnswer(agent, sessionId, channel, message); // reserves a credit; refunds itself on error

  const enc = new TextEncoder();
  const text = (o: unknown) => JSON.stringify(o) + "\n";
  const line = (o: unknown) => enc.encode(text(o));
  const ndjson = { "content-type": "application/x-ndjson; charset=utf-8", "cache-control": "no-store", "x-accel-buffering": "no" };

  if ("handedOff" in prepared) {
    return new NextResponse(text({ type: "handoff", notice: prepared.notice }) + text({ type: "done", citations: [], conversationId: prepared.conversationId }), {
      headers: ndjson,
    });
  }

  const llm = getLLM();
  const abort = new AbortController();

  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      let answer = "";
      let failed = false;
      try {
        for await (const delta of llm.stream({ system: prepared.system, messages: prepared.history, signal: abort.signal })) {
          answer += delta;
          controller.enqueue(line({ type: "delta", text: delta }));
        }
        if (!answer.trim()) throw new Error("The model returned an empty reply");
        controller.enqueue(line({ type: "done", citations: usedCitations(answer, prepared.citations), conversationId: prepared.conversationId }));
      } catch (e) {
        failed = !answer;
        console.error("Chat generation failed:", e);
        if (!abort.signal.aborted) controller.enqueue(line({ type: "error", message: "Sorry, I couldn't answer that right now. Please try again." }));
      } finally {
        if (answer.trim()) await saveAnswer(prepared, answer).catch((e) => console.error("Saving reply failed:", e));
        if (failed) await refundCredit(agent.user_id).catch(() => {});
        try {
          controller.close();
        } catch {
          /* already closed by client abort */
        }
      }
    },
    cancel() {
      abort.abort();
    },
  });

  return new NextResponse(stream, { headers: ndjson });
});
